---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "ghost"
  labels:
    nirmata.io/deployment.name: "ghost"
    nirmata.io/component: "ghost"
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 90
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      nirmata.io/deployment.name: "ghost"
      nirmata.io/component: "ghost"
    matchExpressions: []
  strategy:
    type: "Recreate"
  template:
    metadata:
      annotations: {}
      labels:
        nirmata.io/deployment.name: "ghost"
        nirmata.io/component: "ghost:latest"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      volumes:
      - name: "volume"
        emptyDir: {}
      containers:
      - name: "ghost"
        image: "ghcr.io/nirmata/ghost"
        command: []
        args: []
        ports:
        - name: "http"
          containerPort: 2369
          protocol: "TCP"
